[theme]
primaryColor="#FF4B4B"
backgroundColor="#F5F5F1"
secondaryBackgroundColor="#4B0F1E"
# textColor="#4b0f1e"
textColor="#e00700"
font="sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = false
